import type { Metadata } from 'next'
import './globals.css'
import Head from './head'
import Header from './Header'
import Providers from './Provider'



// export const metadata: Metadata = {
//   title: 'ADNAN NEWS',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <Head/>
      <Providers>      
        <body
        className='bg-gray-200 dark:bg-zinc-900 transition-all duration-700' 
        >
          <Header/>
          <div
          className='max-w-6xl mx-auto'
          >{children}</div>
        </body>
      </Providers>
    </html>
  )
}
